### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#17]
The current site is using jQuery 1.6.4. When this was implemented browsers didn't have the functionality to achieve the same goals with the level of ease that jQuery offered. In modern browsers this is no longer the case and jQuery is not required for the functionality that's being provided here.

While removing jQuery it's important that things like function signatures (names, arguments, and return values), and external element access (i.e. component names and types), are considered immutable since there are areas of the site we aren't using.

## Acceptance Criteria

* jQuery 1.6.4 is no longer used in the site
* Function signatures are kept the same
* The site continues to function as expected
* No negative impact to existing KPIs occurs

**Comment by bp289** [comment]
should we split this ticket up into different functionalities for jquery? so for example one person can work on the search function, and another can work on the cookies?

**Comment by MariamM110** [comment]
Certain sections are in charge of styling, if thats the case:
- Check if the code can be moved straight to css
- If the css will change in any way based on the new update
- Add a `// TODO <ticket reference>` next to this with reference to the ticket to make sure to remove the js once the new design has been implemented

**Comment by SociableSteve** [comment]
We don't have time to action this. It will be included in the 'future plans' section of the handover document
