### ISSUE TITLE
Small changes / fixes

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#172]
- [x] http://redesign-bioconductor-staging.s3-website-us-east-1.amazonaws.com/
- Links to books broken.
- Link ‘Latest release announcement’ broken
- Link ‘Event calendar’ points to the old webste.
 
- [x] http://redesign-bioconductor-staging.s3-website-us-east-1.amazonaws.com/install/
- Replace:
Get latest version of Bioconductor
By
Get the latest version of Bioconductor

- [x] http://redesign-bioconductor-staging.s3-website-us-east-1.amazonaws.com/packages/release/BiocViews.html#___Software
The tree of views on the left goes out of screen to the left when the width of the window is reduced. Only when the window becomes very narrow does the reactive page rearrange items vertically (in a mobile friendly layout).

- [x] http://redesign-bioconductor-staging.s3-website-us-east-1.amazonaws.com/help/docker/
- Can we move the Table of contents to the left side, highlighting the section currently in view (for context), and allowing users to click and jump to other sections (for faster navigation)?

- [x] http://redesign-bioconductor-staging.s3-website-us-east-1.amazonaws.com/help/package-vignettes/
- The font used for strings, e.g. “BioStrings” is weird. Also the font used for keywords, e.g. “for”.

**Comment by MariamM110** [comment]
I cant seem to access any of the links on here 😢
