### ISSUE TITLE
Package listing citation

### ISSUE THREAD

**Issue by bp289** [nearform/bioconductor.org#173]
Citation is missing, this needs to be put back in.

![Image](https://github.com/nearform/bioconductor.org/assets/100142251/dd91f818-1f87-4e17-9ca6-c3859017f79a)

**Comment by SociableSteve** [comment]
Citations are in if the file is present, however styling isn't right. Check out https://www.figma.com/file/nEL17U5Dq4SftPjYlmfc8y/%F0%9F%93%90-Bioconductor.org-(Spec-and-prototype)?type=design&node-id=283-17959&mode=design&t=OQcqW2Zqx6ZLA78b-4 for styling
