### ISSUE TITLE
Start building CSS library

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#18]
There has been some investigation into using SASS as the styling library of choice, however due to the older version of Ruby this isn't going to be possible. The work that has already been done should be retained as much as practical and moved over to CSS.

The goal of this ticket is to add CSS to the site ready for new page designs. Since there are pages we are not updating we should avoid updating existing CSS where possible to ensure unintended side-effects.

The design team have the start of a component library in Figma which can be used as a basis for approaching this work.

## Acceptance Criteria

* There is a new CSS structure in the project
* The new CSS is imported into the homepage

**Comment by bp289** [comment]
Should we wait for #10 to be merged before we start this?

**Comment by MariamM110** [comment]
https://fonts.google.com/specimen/Atkinson+Hyperlegible The link to the font just incase this needs to be changed in the future
- the changes can be found in the _sitehead file

**Comment by SociableSteve** [comment]
There's still some work going on for this, so re-opening the ticket
