### ISSUE TITLE
Implement header - desktop

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#19]
The design team have produced an example header in Figma. While the designs are not yet finalised, the header section is in a good state to implement in readiness for future development. There may be future changes to the design but we have enough to start.

## Acceptance criteria

* The new Header is implemented as per Figma designs
* The homepage now displays the new header
* Other pages still display the old header
* The new header is accessible to WCAG2.1AA
* Items are appropriately tagged for usage reporting purposes
* Design sign-off

**Comment by MariamM110** [comment]
A rough code can be found in this [notion page](https://www.notion.so/nearform/Bioconductor-code-e4ecb368bdc142bcaf6636a9262ed3d1?pvs=4)

**Comment by MariamM110** [comment]
Theres a section on bioconductor.js, that takes care of some of the styling for the header. Its marked as `// TODO implement header`
Once header css is completed, make sure to remove this js as its not needed anymore.
