### ISSUE TITLE
Scroll offset

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#190]
- When you click on a heading in the sidebar in the [Docker page](http://redesign-bioconductor-staging.s3-website-us-east-1.amazonaws.com/help/docker/#usage) it brings you to the correct section but the header is hidden by the top menu. The About page sidebar works fine.
- The Quick Start at the top of the Docker page has bullets on top of the numbered steps.

![Image](https://user-images.githubusercontent.com/52213009/259910491-4bd0b9ec-8153-4b94-b245-a8d83f76718c.png)

**Comment by SociableSteve** [comment]
This should be reviewed wherever we can

**Comment by SociableSteve** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top might be of use here

**Comment by bp289** [comment]
for this, may be able to apply the HTML and css classes from the examples sidebar, as the scrolloffset and styling is already properly set on that.
