### ISSUE TITLE
New page layout

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#25]
The new page layout will be a responsive design up to 1400px in with. Content within that area will have a:

* Default width of (100vh  - 1rem)
* Max width of 1400px

Background colours will strip all the way across the page.

## Acceptance Criteria

* Page content has a max width of 1400px
* Page content has a default width of (100vh - 16px/1rem)
* Page layout is responsive (content will be changed in other tickets)
* Design sign-off

## Considerations

* Google Analytics must still work as before

**Comment by bp289** [comment]
blocked by #20 #40 #19

**Comment by SociableSteve** [comment]
Included in #26
