### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#27]
The homepage is having a major redesign. Implement the new design as per the Figma designs. If this ticket can/should be broken down please feel free to talk with me and we can do that.

## Acceptance criteria

* The new homepage matches the Figma designs
* Design sign off
* The new homepage is accessible
* KPIs must be as good as, or better, than existing KPIs

## Considerations

* Google Analytics must still work as before

**Comment by bp289** [comment]
Breaking this down into #73 #75 #74 #77 #76
