### ISSUE TITLE
Implement header - mobile

### ISSUE THREAD

**Issue by MariamM110** [nearform/bioconductor.org#40]
Ensure that the header is responsive and works on smaller screens than the desktop implementation

## Acceptance Criteria

* Header works on mobile devices as designed in Figma
* Header continues to work on larger screens
* Header changes responsively as the browser/screen changes
* Design sign-off

**Comment by SociableSteve** [comment]
Blocked by #19 and #35

**Comment by MariamM110** [comment]
blocked by #62
