### ISSUE TITLE
Implement footer - mobile

### ISSUE THREAD

**Issue by bp289** [nearform/bioconductor.org#41]
Ensure that the footer is responsive and works on smaller screens than the desktop implementation

## Acceptance Criteria

- Footer works on mobile devices as designed in Figma
- Footer continues to work on larger screens
- Footer changes responsively as the browser/screen change
- Design sign-off

**Comment by SociableSteve** [comment]
Blocked by #20

**Comment by bp289** [comment]
completed this and #51 on the same pull request, since I would require the changes made in the desktop branch, and the responsive design would be easier to do together with seeing how the desktop changes based on how mobile has changed.
