### ISSUE TITLE
KPI automation

### ISSUE THREAD

**Issue by SociableSteve** [nearform/bioconductor.org#7]
Set up automation to measure and report KPIs using Github Actions.

## Acceptance Criteria

* There are tasks run when:
  * A **non-draft** PR is opened/updated
  * The `redesign2023` branch is updated

* The tasks should measure scores for the KPIs as defined in the KPI dashboard:
  * Accessibility
  * Performance scores
  * SEO scores

**Comment by SociableSteve** [comment]
Needs an actual environment to scan. This is waiting for #8

**Comment by bp289** [comment]
Split this ticket into two, the second half is #21
